apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-arm64
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-arm64
  template:
    metadata:
      labels:
        app: demo-arm64
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
        karpenter.sh/nodepool: default
      containers:
        - name: workload
          image: public.ecr.aws/amazonlinux/amazonlinux:2023
          command: ["/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait"]
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
